#!/bin/bash

function createln {
    rm -v ~/$1
    ln -sfv ~/dot-files/$1 ~/$1
}

createln .bashrc
createln .aliases
createln .tmux.conf
createln .vimrc
createln .bash_profile
createln .xinitrc
createln .Xresources
createln .xserverrc
createln bin/progs
createln .progs

# Install vundle
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

# create swapfile dir
mkdir ~/.vim/swapfiles/

# Python3 Support for Vim
echo "Python3 support for vim needed!"
echo
echo "On Debian install with:"
echo "sudo apt install vim-nox"
